# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blockpfGaussianOpt_cpp <- function(data, inlNumber, inlLag) {
    .Call('RcppSMC_blockpfGaussianOpt_cpp', PACKAGE = 'RcppSMC', data, inlNumber, inlLag)
}

LinRegBS_cpp <- function(data, inlNumber) {
    .Call('RcppSMC_LinRegBS_cpp', PACKAGE = 'RcppSMC', data, inlNumber)
}

LinRegLABS_cpp <- function(data, intemps, inlNumber) {
    .Call('RcppSMC_LinRegLABS_cpp', PACKAGE = 'RcppSMC', data, intemps, inlNumber)
}

pfLineartBS_cpp <- function(data, inlNumber, useF, f) {
    .Call('RcppSMC_pfLineartBS_cpp', PACKAGE = 'RcppSMC', data, inlNumber, useF, f)
}

pfNonlinBS_cpp <- function(data, inlNumber) {
    .Call('RcppSMC_pfNonlinBS_cpp', PACKAGE = 'RcppSMC', data, inlNumber)
}

PMMH_cpp <- function(data, inlNumber, lMCMCits) {
    .Call('RcppSMC_PMMH_cpp', PACKAGE = 'RcppSMC', data, inlNumber, lMCMCits)
}

