# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blockpfGaussianOpt_cpp <- function(data, inlNumber, inlLag) {
    .Call('RcppSMC_blockpfGaussianOpt_cpp', PACKAGE = 'RcppSMC', data, inlNumber, inlLag)
}

LinReg_cpp <- function(data, inlNumber) {
    .Call('RcppSMC_LinReg_cpp', PACKAGE = 'RcppSMC', data, inlNumber)
}

LinRegLA_cpp <- function(data, intemps, inlNumber) {
    .Call('RcppSMC_LinRegLA_cpp', PACKAGE = 'RcppSMC', data, intemps, inlNumber)
}

LinRegLA_auto_cpp <- function(data, inlNumber, resampTol, tempTol) {
    .Call('RcppSMC_LinRegLA_auto_cpp', PACKAGE = 'RcppSMC', data, inlNumber, resampTol, tempTol)
}

nonLinPMMH_cpp <- function(data, lNumber, lMCMCits) {
    .Call('RcppSMC_nonLinPMMH_cpp', PACKAGE = 'RcppSMC', data, lNumber, lMCMCits)
}

pfLineartBS_cpp <- function(data, inlNumber, useF, f) {
    .Call('RcppSMC_pfLineartBS_cpp', PACKAGE = 'RcppSMC', data, inlNumber, useF, f)
}

pfNonlinBS_cpp <- function(data, inlNumber) {
    .Call('RcppSMC_pfNonlinBS_cpp', PACKAGE = 'RcppSMC', data, inlNumber)
}

